language: objective-c
xcode_project: PersonnummerExample/PersonnummerExample.xcodeproj # path to your xcodeproj folder
xcode_scheme: PersonnummerExample
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X